# Generated by Django 5.2.3 on 2025-06-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('data_expedicao', models.DateField(verbose_name='Data de Expedição')),
                ('orgao_expedicao', models.CharField(max_length=50, verbose_name='Órgão de Expedição')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('telefone_pessoal', models.CharField(max_length=20, verbose_name='Telefone Pessoal')),
                ('setor', models.CharField(max_length=50, verbose_name='Setor')),
                ('funcao', models.CharField(max_length=50, verbose_name='Função')),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'CLT'), ('MEI', 'MEI')], max_length=3, verbose_name='Tipo de Contrato')),
                ('telefone_corporativo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Corporativo')),
                ('email_corporativo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Corporativo')),
                ('anotacoes', models.TextField(blank=True, null=True, verbose_name='Anotações')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_funcionarios/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
