# Generated by Django 5.2.3 on 2025-06-28 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_funcionario_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cliente')),
                ('gerente_conta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gerente de Conta (GC)')),
                ('telefone_gc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do GC')),
                ('email_gc', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do GC')),
                ('tipo_seguro', models.CharField(blank=True, choices=[('DDR', 'DDR/Carta Conforto'), ('INTALOG', 'Averbado no Seguro Intalog')], max_length=10, null=True, verbose_name='Tipo de Seguro')),
                ('vigencia_pgr', models.DateField(blank=True, null=True, verbose_name='Vigência do PGR')),
                ('pgr_arquivo', models.FileField(blank=True, null=True, upload_to='pgr/', verbose_name='Arquivo PGR (PDF)')),
                ('ddr_arquivo', models.FileField(blank=True, null=True, upload_to='ddr/', verbose_name='Arquivo DDR/Carta (PDF)')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='RegraDeEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mínimo da Carga')),
                ('valor_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Máximo da Carga')),
                ('contrato_frota', models.BooleanField(default=False, verbose_name='Frota')),
                ('contrato_agregado', models.BooleanField(default=False, verbose_name='Agregado')),
                ('contrato_terceiro', models.BooleanField(default=False, verbose_name='Terceiro')),
                ('rastreado', models.BooleanField(default=False, verbose_name='Rastreado')),
                ('isca_movel', models.BooleanField(default=False, verbose_name='Isca Móvel')),
                ('quantidade_iscas', models.CharField(blank=True, choices=[('1', '01'), ('2', '02')], max_length=2, null=True, verbose_name='Quantidade de Iscas')),
                ('escolta', models.BooleanField(default=False, verbose_name='Escolta')),
                ('rastreador_redundancia', models.BooleanField(default=False, verbose_name='Rastreador/Bloqueador de Redundância')),
                ('idade_max_cavalo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade Máxima do Cavalo (anos)')),
                ('idade_max_carreta', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade Máxima da Carreta (anos)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_de_embarque', to='APP.cliente')),
            ],
            options={
                'verbose_name': 'Regra de Embarque',
                'verbose_name_plural': 'Regras de Embarque',
            },
        ),
    ]
