# Generated by Django 5.2.3 on 2025-06-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_cliente_regradeembarque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_apolice', models.CharField(max_length=100, verbose_name='Tipo de Apólice')),
                ('corretora', models.CharField(max_length=100, verbose_name='Corretora')),
                ('corretor', models.CharField(max_length=100, verbose_name='Corretor')),
                ('tel_corretor', models.CharField(max_length=20, verbose_name='Telefone do Corretor')),
                ('email_corretor', models.EmailField(max_length=254, verbose_name='E-mail do Corretor')),
                ('vigencia', models.DateField(verbose_name='Vigência do Seguro')),
                ('descricao', models.TextField(verbose_name='Descrição do Seguro')),
            ],
            options={
                'verbose_name': 'Seguro',
                'verbose_name_plural': 'Seguros',
                'ordering': ['tipo_apolice'],
            },
        ),
    ]
