# Generated by Django 5.2.3 on 2025-06-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguro',
            name='apolice_anexo',
            field=models.FileField(blank=True, null=True, upload_to='apolices/', verbose_name='Anexo da Apólice (PDF)'),
        ),
    ]
