# Generated by Django 5.2.3 on 2025-06-30 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_seguro_apolice_anexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguro',
            options={'ordering': ['cliente__cliente', 'tipo_apolice'], 'verbose_name': 'Seguro', 'verbose_name_plural': 'Seguros'},
        ),
        migrations.AddField(
            model_name='seguro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='APP.cliente', verbose_name='Cliente'),
        ),
    ]
