# Generated by Django 5.2.3 on 2025-06-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_alter_seguro_options_seguro_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Averbacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('tipo_seguro', models.CharField(choices=[('DDR', 'DDR/Carta Conforto'), ('INTALOG', 'Averbado ao Seguro Intalog')], max_length=10, verbose_name='Tipo de Seguro')),
            ],
            options={
                'verbose_name': 'Averbação',
                'verbose_name_plural': 'Averbações',
                'ordering': ['cliente_nome'],
            },
        ),
    ]
