# Generated by Django 5.2.3 on 2025-07-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_averbacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciadoraRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Gerenciadora de Risco')),
                ('validade_condutor_clt', models.PositiveIntegerField(verbose_name='Validade de pesquisa de Condutor CLT (em meses)')),
                ('validade_condutor_agregado', models.PositiveIntegerField(verbose_name='Validade de pesquisa de Condutor Agregado (em meses)')),
                ('validade_condutor_terceiro', models.CharField(default='Por Embarque', max_length=50, verbose_name='Validade de pesquisa de Condutor Terceiro')),
                ('validade_veiculo_frota', models.PositiveIntegerField(verbose_name='Validade de pesquisa de Veículo Frota (em meses)')),
                ('validade_veiculo_agregado', models.PositiveIntegerField(verbose_name='Validade de pesquisa de Veículo Agregado (em meses)')),
                ('validade_veiculo_terceiro', models.CharField(default='Por Embarque', max_length=50, verbose_name='Validade de pesquisa de Veículo Terceiro')),
                ('validade_checklist_frota', models.PositiveIntegerField(verbose_name='Validade de Checklist de Veículo Frota (em dias)')),
                ('validade_checklist_agregado', models.PositiveIntegerField(verbose_name='Validade de Checklist de Veículo Agregado (em dias)')),
                ('validade_checklist_terceiro', models.CharField(default='Por Embarque', max_length=50, verbose_name='Validade de Checklist de Veículo Terceiro')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações diversas')),
            ],
            options={
                'verbose_name': 'Gerenciadora de Risco',
                'verbose_name_plural': 'Gerenciadoras de Risco',
                'ordering': ['nome'],
            },
        ),
    ]
