# Generated by Django 5.2.3 on 2025-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_gerenciadorarisco'),
    ]

    operations = [
        migrations.AddField(
            model_name='averbacao',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='gerenciadorarisco',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='seguro',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='gerenciadorarisco',
            name='validade_checklist_agregado',
            field=models.PositiveIntegerField(verbose_name='Validade de Checklist de Veículo Agregado'),
        ),
        migrations.AlterField(
            model_name='gerenciadorarisco',
            name='validade_checklist_frota',
            field=models.PositiveIntegerField(verbose_name='Validade de Checklist de Veículo Frota'),
        ),
        migrations.AlterField(
            model_name='gerenciadorarisco',
            name='validade_condutor_agregado',
            field=models.PositiveIntegerField(verbose_name='Validade de pesquisa de Condutor Agregado'),
        ),
        migrations.AlterField(
            model_name='gerenciadorarisco',
            name='validade_condutor_clt',
            field=models.PositiveIntegerField(verbose_name='Validade de pesquisa de Condutor CLT'),
        ),
        migrations.AlterField(
            model_name='gerenciadorarisco',
            name='validade_veiculo_agregado',
            field=models.PositiveIntegerField(verbose_name='Validade de pesquisa de Veículo Agregado'),
        ),
        migrations.AlterField(
            model_name='gerenciadorarisco',
            name='validade_veiculo_frota',
            field=models.PositiveIntegerField(verbose_name='Validade de pesquisa de Veículo Frota'),
        ),
    ]
