# Generated by Django 5.2.3 on 2025-08-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_averbacao_data_cadastro_cliente_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguro',
            name='seguradora',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora'),
        ),
    ]
