# Generated by Django 5.2.3 on 2025-08-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0010_averbacao_data_cadastro_cliente_data_cadastro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seguro",
            name="certificado_anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="certificados/",
                verbose_name="Anexo do Certificado (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="seguro",
            name="seguradora",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Seguradora"
            ),
        ),
    ]
