# Generated by Django 5.2.3 on 2025-08-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_seguro_seguradora'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguro',
            name='certificado_anexo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Anexo do Certificado (PDF)'),
        ),
    ]
