# Generated by Django 5.2.3 on 2025-08-24 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0012_sinistro"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistGR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nome da GR"
                    ),
                ),
                (
                    "validade_checklist",
                    models.IntegerField(
                        choices=[(30, "30 dias"), (60, "60 dias"), (90, "90 dias")],
                        verbose_name="Validade do Checklist",
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChecklistVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=10, unique=True, verbose_name="Placa"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[("FROTA", "Frota"), ("AGREGADO", "Agregado")],
                        max_length=10,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("CAVALO", "Cavalo"), ("CARRETA", "Carreta")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rotograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                ("origem", models.CharField(max_length=150, verbose_name="Origem")),
                ("destino", models.CharField(max_length=150, verbose_name="Destino")),
                (
                    "arquivo_pdf",
                    models.FileField(
                        upload_to="rotogramas/", verbose_name="Arquivo (PDF)"
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Rotograma",
                "verbose_name_plural": "Rotogramas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aprovado", models.BooleanField(verbose_name="Aprovado")),
                (
                    "data_aprovacao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Aprovação/Realização",
                    ),
                ),
                (
                    "motivo_reprovacao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo da Reprovação"
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "gr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists",
                        to="APP.checklistgr",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists",
                        to="APP.checklistveiculo",
                    ),
                ),
            ],
            options={
                "unique_together": {("veiculo", "gr")},
            },
        ),
    ]
