# Generated by Django 5.2.3 on 2025-08-13 13:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0012_seguro_certificado_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_sinistro', models.DateTimeField(verbose_name='Data e Hora do Sinistro')),
                ('veiculo_assegurado', models.CharField(max_length=150, verbose_name='Veículo Assegurado')),
                ('seguradora', models.CharField(max_length=100, verbose_name='Seguradora')),
                ('status', models.CharField(choices=[('ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado')], default='ANDAMENTO', max_length=10, verbose_name='Status do Sinistro')),
                ('detalhes', ckeditor.fields.RichTextField(verbose_name='Detalhes')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Sinistro',
                'verbose_name_plural': 'Sinistros',
                'ordering': ['status', '-data_hora_sinistro'],
            },
        ),
    ]
