# Generated by Django 5.2.3 on 2025-08-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0013_sinistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('origem', models.CharField(max_length=150, verbose_name='Origem')),
                ('destino', models.CharField(max_length=150, verbose_name='Destino')),
                ('arquivo_pdf', models.FileField(upload_to='rotogramas/', verbose_name='Arquivo (PDF)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Rotograma',
                'verbose_name_plural': 'Rotogramas',
                'ordering': ['nome'],
            },
        ),
    ]
