# Generated by Django 5.2.3 on 2025-08-25 01:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_checklistgr_checklistveiculo_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreinamentoQSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto do Treinamento')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
                ('hora_evento', models.TimeField(verbose_name='Hora do Evento')),
                ('detalhes', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detalhes')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Treinamento QSMS',
                'verbose_name_plural': 'Treinamentos QSMS',
                'ordering': ['concluido', 'data_evento', 'hora_evento'],
            },
        ),
    ]
