# Generated by Django 5.2.3 on 2025-09-02 14:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0018_permissoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoQSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_certificado', models.CharField(max_length=200, verbose_name='Certificado')),
                ('orgao_competente', models.CharField(max_length=200, verbose_name='Órgão Competente')),
                ('link_orgao', models.URLField(blank=True, null=True, verbose_name='Link do Órgão')),
                ('data_validade', models.DateField(verbose_name='Validade')),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificado QSMS',
                'verbose_name_plural': 'Certificados QSMS',
                'ordering': ['data_validade'],
            },
        ),
        migrations.AlterModelOptions(
            name='permissoes',
            options={'managed': False, 'permissions': [('can_view_dashboard', 'Pode visualizar o Dashboard (Início)'), ('can_view_risk_management_menu', 'Pode visualizar o menu Gerenciamento de Risco'), ('can_view_pgr_list', 'Pode visualizar a lista de PGRs'), ('can_view_gr_list', 'Pode visualizar a lista de Gerenciadoras de Risco'), ('can_view_rotogramas_list', 'Pode visualizar a lista de Rotogramas'), ('can_view_checklist_page', 'Pode visualizar a página de Checklist'), ('can_add_pgr', 'Pode adicionar novo PGR'), ('can_change_pgr', 'Pode editar PGR'), ('can_delete_pgr', 'Pode excluir PGR'), ('can_add_gr', 'Pode adicionar nova Gerenciadora de Risco'), ('can_add_rotograma', 'Pode adicionar novo Rotograma'), ('can_add_checklist_veiculo', 'Pode adicionar veículo no Checklist'), ('can_add_checklist_gr', 'Pode adicionar GR no Checklist'), ('can_add_checklist', 'Pode adicionar/editar um Checklist'), ('can_view_security_menu', 'Pode visualizar o menu Security'), ('can_view_seguros_list', 'Pode visualizar a lista de Seguros'), ('can_view_sinistros_list', 'Pode visualizar a lista de Sinistros'), ('can_view_ddr_list', 'Pode visualizar a lista de DDR'), ('can_add_seguro', 'Pode adicionar novo Seguro'), ('can_view_anexos_seguro', 'Pode visualizar anexos dos Seguros'), ('can_add_sinistro', 'Pode adicionar novo Sinistro'), ('can_change_sinistro', 'Pode editar Sinistro'), ('can_add_ddr', 'Pode adicionar nova Averbação (DDR)'), ('can_view_qsms_menu', 'Pode visualizar o menu QSMS'), ('can_view_treinamentos_list', 'Pode visualizar a Agenda de Treinamentos'), ('can_view_certificados_list', 'Pode visualizar a lista de Certificados'), ('can_add_certificado', 'Pode adicionar novo Certificado'), ('can_add_treinamento', 'Pode adicionar novo Treinamento'), ('can_change_treinamento', 'Pode editar Treinamento'), ('can_view_downloads', 'Pode visualizar a página de Downloads')]},
        ),
    ]
