# Generated by Django 5.2.3 on 2025-09-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0019_certificadoqsms_alter_permissoes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoqsms',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='certificados_qsm/', verbose_name='Anexo (PDF)'),
        ),
    ]
