# Generated by Django 5.2.3 on 2025-09-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0023_veiculoassegurado_alter_permissoes_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklist",
            name="data_validade_manual",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Validade Manual"
            ),
        ),
    ]
