# Generated by Django 5.2.3 on 2025-09-08 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0024_alter_permissoes_options_servicopendente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissoes',
            options={'managed': False, 'permissions': [('can_view_dashboard', 'Pode visualizar o Dashboard (Início)'), ('can_view_risk_management_menu', 'Pode visualizar o menu Gerenciamento de Risco'), ('can_view_pgr_list', 'Pode visualizar a lista de PGRs'), ('can_view_gr_list', 'Pode visualizar a lista de Gerenciadoras de Risco'), ('can_view_rotogramas_list', 'Pode visualizar a lista de Rotogramas'), ('can_view_checklist_page', 'Pode visualizar a página de Checklist'), ('can_view_servicos_pendentes', 'Pode visualizar a página de Serviços Pendentes'), ('can_add_pgr', 'Pode adicionar novo PGR'), ('can_change_pgr', 'Pode editar PGR'), ('can_delete_pgr', 'Pode excluir PGR'), ('can_add_gr', 'Pode adicionar nova Gerenciadora de Risco'), ('can_add_rotograma', 'Pode adicionar novo Rotograma'), ('can_add_checklist_veiculo', 'Pode adicionar veículo no Checklist'), ('can_add_checklist_gr', 'Pode adicionar GR no Checklist'), ('can_add_checklist', 'Pode adicionar/editar um Checklist'), ('can_add_servico_pendente', 'Pode adicionar nova Tarefa Pendente'), ('can_start_servico_pendente', 'Pode iniciar tratativa de Tarefa'), ('can_update_action_servico_pendente', 'Pode gravar ação em Tarefa'), ('can_finalize_servico_pendente', 'Pode finalizar Tarefa'), ('can_view_security_menu', 'Pode visualizar o menu Security'), ('can_view_seguros_list', 'Pode visualizar a lista de Seguros'), ('can_view_sinistros_list', 'Pode visualizar a lista de Sinistros'), ('can_view_ddr_list', 'Pode visualizar a lista de DDR'), ('can_view_contratos_list', 'Pode visualizar a lista de Contratos Diversos'), ('can_add_seguro', 'Pode adicionar novo Seguro'), ('can_view_anexos_seguro', 'Pode visualizar anexos dos Seguros'), ('can_add_sinistro', 'Pode adicionar novo Sinistro'), ('can_change_sinistro', 'Pode editar Sinistro'), ('can_add_ddr', 'Pode adicionar nova Averbação (DDR)'), ('can_add_contrato', 'Pode adicionar novo Contrato Diverso'), ('can_change_contrato', 'Pode editar Contrato Diverso'), ('can_view_qsms_menu', 'Pode visualizar o menu QSMS'), ('can_view_treinamentos_list', 'Pode visualizar a Agenda de Treinamentos'), ('can_view_certificados_list', 'Pode visualizar a lista de Certificados'), ('can_view_eventos_list', 'Pode visualizar o Calendário de Eventos'), ('can_add_treinamento', 'Pode adicionar novo Treinamento'), ('can_change_treinamento', 'Pode editar Treinamento'), ('can_add_certificado', 'Pode adicionar novo Certificado'), ('can_change_certificado', 'Pode editar Certificado'), ('can_add_evento', 'Pode adicionar novo Evento'), ('can_change_evento', 'Pode editar Evento'), ('can_view_downloads', 'Pode visualizar a página de Downloads')]},
        ),
        migrations.RemoveField(
            model_name='servicopendente',
            name='acao_tomada',
        ),
        migrations.CreateModel(
            name='HistoricoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
                ('acao', models.TextField(verbose_name='Ação')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_acoes', to='APP.servicopendente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_acao'],
            },
        ),
    ]
