# Generated by Django 5.2.3 on 2025-09-10 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0025_alter_permissoes_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissoes',
            options={'managed': False, 'permissions': [('can_view_dashboard', 'Pode visualizar o Dashboard (Início)'), ('can_view_risk_management_menu', 'Pode visualizar o menu Gerenciamento de Risco'), ('can_view_pgr_list', 'Pode visualizar a lista de PGRs'), ('can_view_gr_list', 'Pode visualizar a lista de Gerenciadoras de Risco'), ('can_view_rotogramas_list', 'Pode visualizar a lista de Rotogramas'), ('can_view_checklist_page', 'Pode visualizar a página de Checklist'), ('can_view_servicos_pendentes', 'Pode visualizar a página de Serviços Pendentes'), ('can_add_pgr', 'Pode adicionar novo PGR'), ('can_change_pgr', 'Pode editar PGR'), ('can_delete_pgr', 'Pode excluir PGR'), ('can_add_gr', 'Pode adicionar nova Gerenciadora de Risco'), ('can_add_rotograma', 'Pode adicionar novo Rotograma'), ('can_add_checklist_veiculo', 'Pode adicionar veículo no Checklist'), ('can_add_checklist_gr', 'Pode adicionar GR no Checklist'), ('can_add_checklist', 'Pode adicionar/editar um Checklist'), ('can_add_servico_pendente', 'Pode adicionar nova Tarefa Pendente'), ('can_start_servico_pendente', 'Pode iniciar tratativa de Tarefa'), ('can_update_action_servico_pendente', 'Pode gravar ação em Tarefa'), ('can_finalize_servico_pendente', 'Pode finalizar Tarefa'), ('can_view_security_menu', 'Pode visualizar o menu Security'), ('can_view_seguros_list', 'Pode visualizar a lista de Seguros'), ('can_view_sinistros_list', 'Pode visualizar a lista de Sinistros'), ('can_view_ddr_list', 'Pode visualizar a lista de DDR'), ('can_view_contratos_list', 'Pode visualizar a lista de Contratos Diversos'), ('can_add_seguro', 'Pode adicionar novo Seguro'), ('can_view_anexos_seguro', 'Pode visualizar anexos dos Seguros'), ('can_add_sinistro', 'Pode adicionar novo Sinistro'), ('can_change_sinistro', 'Pode editar Sinistro'), ('can_add_ddr', 'Pode adicionar nova Averbação (DDR)'), ('can_add_contrato', 'Pode adicionar novo Contrato Diverso'), ('can_change_contrato', 'Pode editar Contrato Diverso'), ('can_view_qsms_menu', 'Pode visualizar o menu QSMS'), ('can_view_treinamentos_list', 'Pode visualizar a Agenda de Treinamentos'), ('can_view_certificados_list', 'Pode visualizar a lista de Certificados'), ('can_view_eventos_list', 'Pode visualizar o Calendário de Eventos'), ('can_view_servicos_pendentes_qsms', 'Pode visualizar Serviços Pendentes de QSMS'), ('can_add_servico_pendente_qsms', 'Pode adicionar Tarefa Pendente de QSMS'), ('can_start_servico_pendente_qsms', 'Pode iniciar tratativa de Tarefa de QSMS'), ('can_update_action_servico_pendente_qsms', 'Pode gravar ação em Tarefa de QSMS'), ('can_finalize_servico_pendente_qsms', 'Pode finalizar Tarefa de QSMS'), ('can_add_treinamento', 'Pode adicionar novo Treinamento'), ('can_change_treinamento', 'Pode editar Treinamento'), ('can_add_certificado', 'Pode adicionar novo Certificado'), ('can_change_certificado', 'Pode editar Certificado'), ('can_add_evento', 'Pode adicionar novo Evento'), ('can_change_evento', 'Pode editar Evento'), ('can_view_downloads', 'Pode visualizar a página de Downloads')]},
        ),
        migrations.CreateModel(
            name='ServicoPendenteQSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('INICIADO', 'Iniciado'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio_tratativa', models.DateTimeField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_criadas_qsms', to=settings.AUTH_USER_MODEL)),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_finalizadas_qsms', to=settings.AUTH_USER_MODEL)),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_iniciadas_qsms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serviço Pendente QSMS',
                'verbose_name_plural': 'Serviços Pendentes QSMS',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAcaoQSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
                ('acao', models.TextField(verbose_name='Ação')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_acoes_qsms', to='APP.servicopendenteqsms')),
            ],
            options={
                'ordering': ['data_acao'],
            },
        ),
    ]
