# Generated by Django 5.2.7 on 2026-02-03 12:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0028_checklist_data_validade_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicopendente',
            name='descricao',
            field=ckeditor.fields.RichTextField(verbose_name='Descrição'),
        ),
    ]
