# Generated by Django 5.2.3 on 2026-02-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0024_checklist_data_validade_manual"),
        ("APP", "0029_alter_servicopendente_descricao"),
    ]

    operations = []
