# Generated by Django 5.2.7 on 2026-08-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0031_blacklist_alter_permissoes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
    ]
