# Generated by Django 5.2.3 on 2026-09-15 13:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0032_blacklist_data_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='motivo_bloqueio',
            field=ckeditor.fields.RichTextField(verbose_name='Motivo do Bloqueio'),
        ),
    ]
